git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never --no-gitconfig --line-numbers --navigate
  # pagers:
  #   - pager: delta --dark --paging=never --no-gitconfig --line-numbers --navigate
